project_id = "asjhkidpuhqodryczuth"

[functions.create-admin-user]
verify_jwt = false

[functions.r2-upload-url]
verify_jwt = false

[functions.generate-content]
verify_jwt = false

[functions.r2-read-url]
verify_jwt = false

[functions.google-account-info]
verify_jwt = false

[functions.youtube-save-connection]
verify_jwt = false

[functions.post-scheduled-content]
verify_jwt = false

[functions.r2-multipart-upload]
verify_jwt = false

[functions.extract-shorts]
verify_jwt = false

[functions.youtube-get-access-token]
verify_jwt = false
