-- =========================================
-- ENUMS
-- =========================================
CREATE TYPE public.app_role AS ENUM ('admin', 'user', 'influencer');
CREATE TYPE public.post_status AS ENUM ('incomplete', 'unscheduled', 'scheduled', 'posted', 'scripted');
CREATE TYPE public.video_length AS ENUM ('Short', 'Long', 'Both');

-- =========================================
-- HELPER: set_updated_at
-- =========================================
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- =========================================
-- USER ROLES (must exist before has_role)
-- =========================================
CREATE TABLE public.user_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  role app_role NOT NULL,
  UNIQUE (user_id, role)
);
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- =========================================
-- HELPER: has_role
-- =========================================
CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role app_role)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = _user_id AND role = _role
  )
$$;

CREATE POLICY "Users can read own roles" ON public.user_roles
  FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Admins can read all roles" ON public.user_roles
  FOR SELECT TO authenticated USING (has_role(auth.uid(), 'admin'));

CREATE INDEX idx_user_roles_user_id ON public.user_roles(user_id);

-- =========================================
-- PROFILES
-- =========================================
CREATE TABLE public.profiles (
  id uuid PRIMARY KEY,
  email text NOT NULL,
  display_name text,
  password text,
  onboarding_completed boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users read own profile" ON public.profiles
  FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY "Admins read all profiles" ON public.profiles
  FOR SELECT TO authenticated USING (has_role(auth.uid(), 'admin'));
CREATE POLICY "Users update own profile" ON public.profiles
  FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

CREATE TRIGGER profiles_set_updated_at BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =========================================
-- PLAYLISTS
-- =========================================
CREATE TABLE public.playlists (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  playlist_title text,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.playlists ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated select playlists" ON public.playlists
  FOR SELECT USING (true);

-- =========================================
-- CONTENT IDEAS
-- =========================================
CREATE TABLE public.content_ideas (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL,
  playlist_id bigint REFERENCES public.playlists(id) ON DELETE SET NULL,
  length video_length DEFAULT 'Both',
  avatar text,
  category text,
  topic text,
  planned_date timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.content_ideas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users select own ideas" ON public.content_ideas
  FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users insert own ideas" ON public.content_ideas
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own ideas" ON public.content_ideas
  FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users delete own ideas" ON public.content_ideas
  FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Admins full access ideas" ON public.content_ideas
  FOR ALL TO authenticated USING (has_role(auth.uid(), 'admin')) WITH CHECK (has_role(auth.uid(), 'admin'));

CREATE INDEX idx_content_ideas_user_id ON public.content_ideas(user_id);

-- =========================================
-- SOCIAL CONTENT
-- =========================================
CREATE TABLE public.social_content (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  parent_content_id uuid REFERENCES public.social_content(id) ON DELETE SET NULL,
  playlist_id bigint REFERENCES public.playlists(id) ON DELETE SET NULL,
  topic text NOT NULL,
  post_title text,
  post_length video_length,
  status post_status NOT NULL DEFAULT 'incomplete',
  script text,
  planned_date timestamptz,
  scheduled_at timestamptz,
  scheduled_platforms text[],
  posted_at timestamptz,
  upload_at timestamptz,
  image text,
  video_url text,
  video_storage_path text,
  video_original_filename text,
  video_mime_type text,
  video_size_bytes bigint,
  ig_tiktok_desc text,
  facebook_desc text,
  linkedin_desc text,
  youtube_desc text,
  youtube_status text,
  youtube_video_id text,
  youtube_uploaded_at timestamptz,
  youtube_error_detail text,
  youtube_comment text,
  youtube_comment_status text,
  youtube_comment_id text,
  youtube_comment_posted_at timestamptz,
  youtube_comment_error_detail text,
  error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.social_content ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can select own content" ON public.social_content
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own content" ON public.social_content
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own content" ON public.social_content
  FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own content" ON public.social_content
  FOR DELETE USING (auth.uid() = user_id);
CREATE POLICY "Admins can select all content" ON public.social_content
  FOR SELECT USING (has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins can insert all content" ON public.social_content
  FOR INSERT WITH CHECK (has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins can update all content" ON public.social_content
  FOR UPDATE USING (has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins can delete all content" ON public.social_content
  FOR DELETE USING (has_role(auth.uid(), 'admin'));

CREATE TRIGGER social_content_set_updated_at BEFORE UPDATE ON public.social_content
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE INDEX idx_social_content_user_id ON public.social_content(user_id);
CREATE INDEX idx_social_content_status ON public.social_content(status);
CREATE INDEX idx_social_content_scheduled_at ON public.social_content(scheduled_at);
CREATE INDEX idx_social_content_youtube_status ON public.social_content(youtube_status);

-- =========================================
-- POSTED CONTENT
-- =========================================
CREATE TABLE public.posted_content (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  source_content_id uuid,
  parent_content_id uuid,
  playlist_id bigint REFERENCES public.playlists(id) ON DELETE SET NULL,
  topic text NOT NULL,
  post_title text,
  post_length video_length,
  status post_status NOT NULL DEFAULT 'posted',
  planned_date timestamptz,
  scheduled_at timestamptz,
  scheduled_platforms text[],
  posted_at timestamptz,
  image text,
  image_url text,
  video_url text,
  video_storage_path text,
  video_original_filename text,
  video_mime_type text,
  ig_tiktok_desc text,
  facebook_desc text,
  linkedin_desc text,
  youtube_title text,
  youtube_desc text,
  youtube_video_id text,
  youtube_comment text,
  youtube_comment_status text,
  youtube_comment_id text,
  youtube_comment_posted_at timestamptz,
  youtube_comment_error_detail text,
  tiktok_status text,
  tiktok_error text,
  tiktok_job_id text,
  error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.posted_content ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can select own posted content" ON public.posted_content
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Admins can select all posted content" ON public.posted_content
  FOR SELECT USING (has_role(auth.uid(), 'admin'));
CREATE POLICY "Public can view published long content" ON public.posted_content
  FOR SELECT TO anon, authenticated
  USING (post_length = 'Long' AND youtube_video_id IS NOT NULL AND status = 'posted');

CREATE TRIGGER posted_content_set_updated_at BEFORE UPDATE ON public.posted_content
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE INDEX idx_posted_content_user_id ON public.posted_content(user_id);
CREATE INDEX idx_posted_content_source ON public.posted_content(source_content_id);

-- =========================================
-- CONTENT INSTRUCTION DEFAULTS
-- =========================================
CREATE TABLE public.content_instruction_defaults (
  scope text PRIMARY KEY,
  instruction text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.content_instruction_defaults ENABLE ROW LEVEL SECURITY;

CREATE POLICY "All authenticated can read defaults" ON public.content_instruction_defaults
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins can insert defaults" ON public.content_instruction_defaults
  FOR INSERT TO authenticated WITH CHECK (has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins can update defaults" ON public.content_instruction_defaults
  FOR UPDATE TO authenticated USING (has_role(auth.uid(), 'admin')) WITH CHECK (has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins can delete defaults" ON public.content_instruction_defaults
  FOR DELETE TO authenticated USING (has_role(auth.uid(), 'admin'));

CREATE TRIGGER cid_set_updated_at BEFORE UPDATE ON public.content_instruction_defaults
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =========================================
-- USER CONTENT INSTRUCTIONS
-- =========================================
CREATE TABLE public.user_content_instructions (
  user_id uuid NOT NULL,
  scope text NOT NULL,
  instruction text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, scope)
);
ALTER TABLE public.user_content_instructions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users select own instructions" ON public.user_content_instructions
  FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users insert own instructions" ON public.user_content_instructions
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own instructions" ON public.user_content_instructions
  FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users delete own instructions" ON public.user_content_instructions
  FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Admins read all user instructions" ON public.user_content_instructions
  FOR SELECT TO authenticated USING (has_role(auth.uid(), 'admin'));

CREATE TRIGGER uci_set_updated_at BEFORE UPDATE ON public.user_content_instructions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =========================================
-- YOUTUBE CONNECTIONS
-- =========================================
CREATE TABLE public.youtube_connections (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  refresh_token text NOT NULL,
  channel_id text,
  channel_title text,
  google_email text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.youtube_connections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can select own connection" ON public.youtube_connections
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own connection" ON public.youtube_connections
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own connection" ON public.youtube_connections
  FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own connection" ON public.youtube_connections
  FOR DELETE USING (auth.uid() = user_id);

CREATE TRIGGER yc_set_updated_at BEFORE UPDATE ON public.youtube_connections
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =========================================
-- AUTH + INSTRUCTION SEEDING
-- =========================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, onboarding_completed)
  VALUES (NEW.id, NEW.email, false)
  ON CONFLICT (id) DO NOTHING;

  INSERT INTO public.user_roles (user_id, role)
  VALUES (NEW.id, 'user')
  ON CONFLICT DO NOTHING;

  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE OR REPLACE FUNCTION public.seed_user_instructions()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.user_content_instructions (user_id, scope, instruction)
  SELECT NEW.id, d.scope, d.instruction
  FROM public.content_instruction_defaults d
  ON CONFLICT (user_id, scope) DO NOTHING;
  RETURN NEW;
END;
$$;

CREATE TRIGGER seed_instructions_after_profile_insert
  AFTER INSERT ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.seed_user_instructions();

-- =========================================
-- SOCIAL CONTENT BUSINESS LOGIC TRIGGERS
-- =========================================
CREATE OR REPLACE FUNCTION public.auto_promote_incomplete()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF NEW.status = 'incomplete' THEN
    IF coalesce(NEW.video_storage_path, '') <> ''
       AND coalesce(NEW.post_title, '') <> ''
       AND NEW.post_length IS NOT NULL
    THEN
      IF NEW.post_length::text = 'Short'
         OR coalesce(NEW.image, '') <> ''
      THEN
        NEW.status := 'unscheduled';
      END IF;
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER social_content_auto_promote
  BEFORE INSERT OR UPDATE ON public.social_content
  FOR EACH ROW EXECUTE FUNCTION public.auto_promote_incomplete();

CREATE OR REPLACE FUNCTION public.enforce_youtube_schedule_requirements()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF NEW.scheduled_at IS NOT NULL THEN
    IF NEW.post_length IS DISTINCT FROM 'Short' AND coalesce(NEW.image, '') = '' THEN
      RAISE EXCEPTION 'Cannot schedule: image is missing';
    END IF;
    IF coalesce(NEW.video_storage_path, '') = '' THEN
      RAISE EXCEPTION 'Cannot schedule: video_storage_path is missing';
    END IF;
    IF coalesce(NEW.post_title, '') = '' THEN
      RAISE EXCEPTION 'Cannot schedule: post_title is missing';
    END IF;
    IF NEW.post_length IS DISTINCT FROM 'Short' AND coalesce(NEW.youtube_desc, '') = '' THEN
      RAISE EXCEPTION 'Cannot schedule: youtube_desc is missing';
    END IF;
    IF NEW.post_length IS NULL THEN
      RAISE EXCEPTION 'Cannot schedule: post_length is missing';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER social_content_enforce_schedule
  BEFORE INSERT OR UPDATE ON public.social_content
  FOR EACH ROW EXECUTE FUNCTION public.enforce_youtube_schedule_requirements();

CREATE OR REPLACE FUNCTION public.set_youtube_upload_at_and_queue()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  buffer interval;
  pl text;
BEGIN
  pl := CASE WHEN NEW.post_length IS NULL THEN NULL ELSE lower(NEW.post_length::text) END;

  IF NEW.scheduled_at IS NOT NULL AND (
       TG_OP = 'INSERT'
       OR NEW.scheduled_at IS DISTINCT FROM OLD.scheduled_at
       OR NEW.post_length IS DISTINCT FROM OLD.post_length
     )
  THEN
    IF pl = 'long' THEN
      buffer := interval '6 hours';
    ELSE
      buffer := interval '2 hours';
    END IF;

    IF NEW.upload_at IS NULL THEN
      NEW.upload_at := greatest(now(), NEW.scheduled_at - buffer);
    END IF;

    IF NEW.youtube_status IS NULL OR NEW.youtube_status IN ('draft','pending','queued') THEN
      NEW.youtube_status := 'queued';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER social_content_set_upload_at
  BEFORE INSERT OR UPDATE ON public.social_content
  FOR EACH ROW EXECUTE FUNCTION public.set_youtube_upload_at_and_queue();

CREATE OR REPLACE FUNCTION public.sync_youtube_video_id_to_posted()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.youtube_video_id IS NOT NULL
     AND (OLD.youtube_video_id IS DISTINCT FROM NEW.youtube_video_id)
  THEN
    UPDATE posted_content
       SET youtube_video_id = NEW.youtube_video_id
     WHERE source_content_id = NEW.id;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER social_content_sync_yt_id
  AFTER UPDATE ON public.social_content
  FOR EACH ROW EXECUTE FUNCTION public.sync_youtube_video_id_to_posted();

CREATE OR REPLACE FUNCTION public.reset_stuck_youtube_uploads(minutes_stuck integer DEFAULT 30)
RETURNS integer
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  n int;
BEGIN
  UPDATE public.social_content
  SET
    youtube_status = 'queued',
    upload_at = now(),
    youtube_error_detail = 'Auto-reset: stuck in uploading > ' || minutes_stuck || ' minutes',
    youtube_video_id = NULL,
    youtube_uploaded_at = NULL
  WHERE youtube_status = 'uploading'
    AND upload_at IS NOT NULL
    AND upload_at < now() - make_interval(mins => minutes_stuck);

  GET DIAGNOSTICS n = row_count;
  RETURN n;
END;
$$;

-- =========================================
-- STORAGE BUCKETS
-- =========================================
INSERT INTO storage.buckets (id, name, public) VALUES ('avatars', 'avatars', true);
INSERT INTO storage.buckets (id, name, public) VALUES ('content-media', 'content-media', false);

CREATE POLICY "Avatar images are publicly accessible"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'avatars');

CREATE POLICY "Users can upload their own avatar"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'avatars' AND auth.uid()::text = (storage.foldername(name))[1]);

CREATE POLICY "Users can update their own avatar"
  ON storage.objects FOR UPDATE
  USING (bucket_id = 'avatars' AND auth.uid()::text = (storage.foldername(name))[1]);

CREATE POLICY "Users can delete their own avatar"
  ON storage.objects FOR DELETE
  USING (bucket_id = 'avatars' AND auth.uid()::text = (storage.foldername(name))[1]);

CREATE POLICY "Users can view own content media"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'content-media' AND auth.uid()::text = (storage.foldername(name))[1]);

CREATE POLICY "Users can upload own content media"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'content-media' AND auth.uid()::text = (storage.foldername(name))[1]);

CREATE POLICY "Users can update own content media"
  ON storage.objects FOR UPDATE
  USING (bucket_id = 'content-media' AND auth.uid()::text = (storage.foldername(name))[1]);

CREATE POLICY "Users can delete own content media"
  ON storage.objects FOR DELETE
  USING (bucket_id = 'content-media' AND auth.uid()::text = (storage.foldername(name))[1]);