-- Billing Hub Supabase project: ahqauomkgflopxgnlndd
-- Applied live on 2026-10-02. Kept here as an auditable schema contract.

begin;

alter table public.ai_operations_video_jobs
  drop constraint if exists ai_operations_video_jobs_job_type_check;

alter table public.ai_operations_video_jobs
  add constraint ai_operations_video_jobs_job_type_check
  check (job_type = any (array[
    'transcribe'::text,
    'render_clip'::text,
    'publish_youtube'::text,
    'refresh_source_metadata'::text,
    'concat_video'::text
  ]));

alter table public.ai_operations_video_jobs
  add column if not exists progress jsonb not null default '{}'::jsonb,
  add column if not exists result jsonb not null default '{}'::jsonb,
  add column if not exists idempotency_key text;

create unique index if not exists ai_operations_video_jobs_tenant_idempotency_key_uq
  on public.ai_operations_video_jobs (tenant_id, idempotency_key)
  where idempotency_key is not null;

create table if not exists public.ai_operations_video_job_inputs (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.ai_operations_video_jobs(id) on delete cascade,
  position integer not null check (position > 0),
  drive_file_id text not null,
  drive_file_name text not null,
  drive_folder_id text,
  mime_type text,
  size_bytes bigint check (size_bytes is null or size_bytes >= 0),
  modified_time timestamptz,
  created_at timestamptz not null default now(),
  unique (job_id, position)
);

create index if not exists ai_operations_video_job_inputs_job_id_idx
  on public.ai_operations_video_job_inputs(job_id);

alter table public.ai_operations_video_job_inputs enable row level security;

revoke all on table public.ai_operations_video_job_inputs from anon, authenticated;
revoke all on sequence public.ai_operations_video_job_inputs_id_seq from anon, authenticated;
grant all on table public.ai_operations_video_job_inputs to service_role;
grant usage, select on sequence public.ai_operations_video_job_inputs_id_seq to service_role;

commit;
